services:
  postgres:
    image: postgres:latest
    container_name: tttb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tttb_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json
    container_name: tttb_api
